/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mymodule */

#ifndef _Included_Mymodule
#define _Included_Mymodule
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_Mymodule_solve(JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
